name: flutter_svprogresshud
description: A clean and lightweight progress HUD for flutter app, based on SVProgressHUD.
version: 1.1.0
homepage: https://github.com/leanflutter/flutter_svprogresshud

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.1

flutter:
  plugin:
    platforms:
      android:
        package: org.leanflutter.plugins.flutter_svprogresshud
        pluginClass: FlutterSvprogresshudPlugin
      ios:
        pluginClass: FlutterSvprogresshudPlugin
